@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.anvilcraft.guideme.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;